[package]
name = "aetherus-remesh"
version = "0.4.3"
authors = ["Cristian Bourceanu <v.c.bourceanu@smd.ed.ac.uk>"]
edition = "2024"
description = "Mesh splitting algorithm for co-planar intersection, used in MCRT simulation"
repository = "https://github.com/crisbour/aetherus-remesh"
readme = "README.md"
license = "MIT"
keywords = ["remesh", "obj", "MCRT"]
categories = ["science", "simulation"]
exclude = [".github"]

[dependencies]
anyhow = "^1.0.100"
assert_approx_eq = "^1.1.0"
colored = "3.1.1"
env_logger = "^0.11.0"
kiddo = { version = "^5.3.2", features = ["simd"] }
log = "^0.4.29"
nalgebra = "^0.31.*"
obj = { git = "https://github.com/kvark/obj", branch = "master", version="0.10.2", optional = true }
tobj = { version = "4.0.3", optional = true }

[dev-dependencies]
assert_approx_eq = "1.1.0"
criterion = { version = "0.8.2", features = ["html_reports"] }
gungraun = "0.17.2"
tempfile = "3.27.0"

[features]
release-logging = ["log/max_level_info"]
obj = [ "dep:obj" ]
tobj = [ "dep:tobj" ]

[[bench]]
name = "water_tank"
harness = false

[[bench]]
name = "water_tank_instructions"
harness = false

[[bin]]
name = "remesh"
path = "src/main.rs"
required-features = ["obj"]
